apiVersion: v1
kind: Pod
metadata:
  name: my-webcolor
  labels:
    name: webcolor
spec:
  containers:
    - name: webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /opt/
          name: app-secret-volumes
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret